export enum Path {
  SPLASH_SCREEN = 'Splash',
  LOGIN_SCREEN = 'Login',
  FORGOT_PASSWORD_EMAIL_SCREEN = 'ForgotPasswordEmail',
  PASSWORD_RESET_SUCCESSFUL_SCREEN = 'PasswordResetSuccessful',
  CREATE_NEW_PASSWORD_SCREEN = 'CreateNewPassword',
  SELECT_ROLE_SCREEN = 'SelectRole',
  SIGNUP_EMAIL_SCREEN = 'SignupEmail',
  SIGNUP_SCREEN = 'Signup',
  OTP_SCREEN = 'Otp',
  REGISTRATION_FORM_SCREEN = 'RegistrationForm',
  PREVIEW_FORM_SCREEN = 'PreviewForm',
  PASSWORD_SCREEN = 'PasswordScreen',
  
  /// Auth Stack
  BOTTOM_TABS = 'BottomTabs',
  HOME_STACK= 'HomeStack',
  WISHLIST_STACK= 'WishlistStack',
  TOOLS_STACK= 'ToolsStack',
  CART_STACK= 'CartStack',
  MESSAGES_STACK = "MessagesStack",
  PROFILE_STACK= 'ProfileStack',
  HOME_SCREEN = 'Home',
  NOTIFICATION_SCREEN = 'Notification',
  APPINION_REQUEST_SCREEN = 'AppinionRequest',
  APPINION_REQUEST_PREVIEW_SCREEN = 'AppinionRequestPreview',
  TOOLS_SCREEN = 'Tools',
  CONTACTS_SCREEN = 'Contacts',
  ADD_PRODUCTS_SCREEN = 'AddProducts',
  PRODUCTS_SCREEN = 'Products',
  PRODUCT_DETAILS_SCREEN = 'ProductDetails',
  ORDERS_SCREEN = 'Orders',
  CHAT_SCREEN = 'Chat',
  APPINIONS_SCREEN = 'Appinions',
  PROFILE_SCREEN = 'Profile',
  ABOUT_SCREEN = 'About',
  TERMS_SCREEN = 'Terms',
  PRIVACY_POLICY_SCREEN = 'PrivacyPolicy',
  FAQS_SCREEN = 'Faqs',
  PRICING_SCREEN = 'Pricing',
  FEEDBACK_SCREEN = 'Feedback',
  TRACK_SALES_SCREEN = 'TrackSales',
  TRACK_TOTAL_SALES_SCREEN = 'TrackTotalSales',
 
}
