export enum Path {
  SPLASH_SCREEN = 'Splash',
  LOGIN_SCREEN = 'Login',
  FORGOT_PASSWORD_EMAIL_SCREEN = 'ForgotPasswordEmail',
  PASSWORD_RESET_SUCCESSFUL_SCREEN = 'PasswordResetSuccessful',
  CREATE_NEW_PASSWORD_SCREEN = 'CreateNewPassword',
  SELECT_ROLE_SCREEN = 'SelectRole',
  SIGNUP_EMAIL_SCREEN = 'SignupEmail',
  OTP_SCREEN = 'Otp',
  REGISTRATION_FORM_SCREEN = 'RegistrationForm',
  PREVIEW_FORM_SCREEN = 'PreviewForm',
  PASSWORD_SCREEN = 'PasswordScreen',
  
  /// Auth Stack
  BOTTOM_TABS = 'BottomTabs',
  HOME_STACK= 'HomeStack',
  MEDICAL_INFO_STACK= 'MedicalInfoStack',
  PROFILE_STACK= 'ProfileStack',
  HOME_SCREEN = 'Home',
  NOTIFICATION_SCREEN = 'Notification',
  APPINION_REQUEST_SCREEN = 'AppinionRequest',
  APPINION_REQUEST_PREVIEW_SCREEN = 'AppinionRequestPreview',
  MEDICAL_INFO_SCREEN = 'MedicalInfo',
  ADD_MEDICAL_INFO_SCREEN = 'AddMedicalInfo',
  APPINIONS_SCREEN = 'Appinions',
  PROFILE_SCREEN = 'Profile',
  ABOUT_SCREEN = 'About',
  TERMS_SCREEN = 'Terms',
  PRIVACY_POLICY_SCREEN = 'PrivacyPolicy',
  FAQS_SCREEN = 'Faqs',
  PRICING_SCREEN = 'Pricing',
  FEEDBACK_SCREEN = 'Feedback',
 
}
