//  This file is auto-generated and read-only
import {makeIconWeb} from './utils/makeIconWeb';
import {ReactComponent as IconAboutSvg} from '~Assets/Icons/about.svg';
import {ReactComponent as IconAddSvg} from '~Assets/Icons/add.svg';
import {ReactComponent as IconAddProductsSvg} from '~Assets/Icons/addProducts.svg';
import {ReactComponent as IconAppinionsActiveSvg} from '~Assets/Icons/appinionsActive.svg';
import {ReactComponent as IconAppinionsInActiveSvg} from '~Assets/Icons/appinionsInActive.svg';
import {ReactComponent as IconArrowDownSvg} from '~Assets/Icons/arrowDown.svg';
import {ReactComponent as IconBankSvg} from '~Assets/Icons/bank.svg';
import {ReactComponent as IconCardiologySvg} from '~Assets/Icons/cardiology.svg';
import {ReactComponent as IconCheckSvg} from '~Assets/Icons/check.svg';
import {ReactComponent as IconChevronleftSvg} from '~Assets/Icons/chevronleft.svg';
import {ReactComponent as IconConvertSvg} from '~Assets/Icons/convert.svg';
import {ReactComponent as IconCrossSvg} from '~Assets/Icons/cross.svg';
import {ReactComponent as IconDermatologySvg} from '~Assets/Icons/dermatology.svg';
import {ReactComponent as IconDocumentSvg} from '~Assets/Icons/document.svg';
import {ReactComponent as IconEditSvg} from '~Assets/Icons/edit.svg';
import {ReactComponent as IconEmailSvg} from '~Assets/Icons/email.svg';
import {ReactComponent as IconEyeSvg} from '~Assets/Icons/eye.svg';
import {ReactComponent as IconEyeHideSvg} from '~Assets/Icons/eyeHide.svg';
import {ReactComponent as IconFaqsSvg} from '~Assets/Icons/faqs.svg';
import {ReactComponent as IconFeedbackSvg} from '~Assets/Icons/feedback.svg';
import {ReactComponent as IconGallerySvg} from '~Assets/Icons/gallery.svg';
import {ReactComponent as IconGoogleSvg} from '~Assets/Icons/google.svg';
import {ReactComponent as IconHamburgerSvg} from '~Assets/Icons/hamburger.svg';
import {ReactComponent as IconHomeActiveSvg} from '~Assets/Icons/homeActive.svg';
import {ReactComponent as IconHomeInActiveSvg} from '~Assets/Icons/homeInActive.svg';
import {ReactComponent as IconIncomeSvg} from '~Assets/Icons/income.svg';
import {ReactComponent as IconInfoCircleSvg} from '~Assets/Icons/infoCircle.svg';
import {ReactComponent as IconLockSvg} from '~Assets/Icons/lock.svg';
import {ReactComponent as IconMailSvg} from '~Assets/Icons/mail.svg';
import {ReactComponent as IconMedicalInfoActiveSvg} from '~Assets/Icons/medicalInfoActive.svg';
import {ReactComponent as IconMedicalInfoInActiveSvg} from '~Assets/Icons/medicalInfoInActive.svg';
import {ReactComponent as IconMenuSvg} from '~Assets/Icons/menu.svg';
import {ReactComponent as IconMessageActiveSvg} from '~Assets/Icons/messageActive.svg';
import {ReactComponent as IconMessageInactiveSvg} from '~Assets/Icons/messageInactive.svg';
import {ReactComponent as IconMicActiveSvg} from '~Assets/Icons/micActive.svg';
import {ReactComponent as IconMicInactiveSvg} from '~Assets/Icons/micInactive.svg';
import {ReactComponent as IconMyProductsSvg} from '~Assets/Icons/myProducts.svg';
import {ReactComponent as IconNeurologySvg} from '~Assets/Icons/neurology.svg';
import {ReactComponent as IconNotificationSvg} from '~Assets/Icons/notification.svg';
import {ReactComponent as IconOrdersSvg} from '~Assets/Icons/orders.svg';
import {ReactComponent as IconPakistanSvg} from '~Assets/Icons/pakistan.svg';
import {ReactComponent as IconPatientSvg} from '~Assets/Icons/patient.svg';
import {ReactComponent as IconPaymentSvg} from '~Assets/Icons/payment.svg';
import {ReactComponent as IconPricingSvg} from '~Assets/Icons/pricing.svg';
import {ReactComponent as IconPrivacyPolicySvg} from '~Assets/Icons/privacyPolicy.svg';
import {ReactComponent as IconProductSvg} from '~Assets/Icons/product.svg';
import {ReactComponent as IconProfileActiveSvg} from '~Assets/Icons/profileActive.svg';
import {ReactComponent as IconProfileInActiveSvg} from '~Assets/Icons/profileInActive.svg';
import {ReactComponent as IconRespiratorySvg} from '~Assets/Icons/respiratory.svg';
import {ReactComponent as IconReturnOrdersSvg} from '~Assets/Icons/returnOrders.svg';
import {ReactComponent as IconReviewsSvg} from '~Assets/Icons/reviews.svg';
import {ReactComponent as IconRightArrowSvg} from '~Assets/Icons/rightArrow.svg';
import {ReactComponent as IconRightArrowGraySvg} from '~Assets/Icons/rightArrowGray.svg';
import {ReactComponent as IconRightArrowWhiteSvg} from '~Assets/Icons/rightArrowWhite.svg';
import {ReactComponent as IconSearchSvg} from '~Assets/Icons/search.svg';
import {ReactComponent as IconShareSvg} from '~Assets/Icons/share.svg';
import {ReactComponent as IconShopSvg} from '~Assets/Icons/shop.svg';
import {ReactComponent as IconSignOutSvg} from '~Assets/Icons/signOut.svg';
import {ReactComponent as IconSpecialistSvg} from '~Assets/Icons/specialist.svg';
import {ReactComponent as IconTermsSvg} from '~Assets/Icons/terms.svg';
import {ReactComponent as IconTickCircleSvg} from '~Assets/Icons/tickCircle.svg';
import {ReactComponent as IconToolsActiveSvg} from '~Assets/Icons/toolsActive.svg';
import {ReactComponent as IconToolsInactiveSvg} from '~Assets/Icons/toolsInactive.svg';
import {ReactComponent as IconTrackSalesSvg} from '~Assets/Icons/trackSales.svg';
import {ReactComponent as IconTrackSalesDarkSvg} from '~Assets/Icons/trackSalesDark.svg';
import {ReactComponent as IconTrackSalesGreenSvg} from '~Assets/Icons/trackSalesGreen.svg';
import {ReactComponent as IconTrackSalesLightSvg} from '~Assets/Icons/trackSalesLight.svg';
import {ReactComponent as IconTrackSalesYellowSvg} from '~Assets/Icons/trackSalesYellow.svg';
import {ReactComponent as IconUserSvg} from '~Assets/Icons/user.svg';
import {ReactComponent as IconVerifySvg} from '~Assets/Icons/verify.svg';

export * from './props';

export const IconAbout = makeIconWeb(IconAboutSvg);
export const IconAdd = makeIconWeb(IconAddSvg);
export const IconAddProducts = makeIconWeb(IconAddProductsSvg);
export const IconAppinionsActive = makeIconWeb(IconAppinionsActiveSvg);
export const IconAppinionsInActive = makeIconWeb(IconAppinionsInActiveSvg);
export const IconArrowDown = makeIconWeb(IconArrowDownSvg);
export const IconBank = makeIconWeb(IconBankSvg);
export const IconCardiology = makeIconWeb(IconCardiologySvg);
export const IconCheck = makeIconWeb(IconCheckSvg);
export const IconChevronleft = makeIconWeb(IconChevronleftSvg);
export const IconConvert = makeIconWeb(IconConvertSvg);
export const IconCross = makeIconWeb(IconCrossSvg);
export const IconDermatology = makeIconWeb(IconDermatologySvg);
export const IconDocument = makeIconWeb(IconDocumentSvg);
export const IconEdit = makeIconWeb(IconEditSvg);
export const IconEmail = makeIconWeb(IconEmailSvg);
export const IconEye = makeIconWeb(IconEyeSvg);
export const IconEyeHide = makeIconWeb(IconEyeHideSvg);
export const IconFaqs = makeIconWeb(IconFaqsSvg);
export const IconFeedback = makeIconWeb(IconFeedbackSvg);
export const IconGallery = makeIconWeb(IconGallerySvg);
export const IconGoogle = makeIconWeb(IconGoogleSvg);
export const IconHamburger = makeIconWeb(IconHamburgerSvg);
export const IconHomeActive = makeIconWeb(IconHomeActiveSvg);
export const IconHomeInActive = makeIconWeb(IconHomeInActiveSvg);
export const IconIncome = makeIconWeb(IconIncomeSvg);
export const IconInfoCircle = makeIconWeb(IconInfoCircleSvg);
export const IconLock = makeIconWeb(IconLockSvg);
export const IconMail = makeIconWeb(IconMailSvg);
export const IconMedicalInfoActive = makeIconWeb(IconMedicalInfoActiveSvg);
export const IconMedicalInfoInActive = makeIconWeb(IconMedicalInfoInActiveSvg);
export const IconMenu = makeIconWeb(IconMenuSvg);
export const IconMessageActive = makeIconWeb(IconMessageActiveSvg);
export const IconMessageInactive = makeIconWeb(IconMessageInactiveSvg);
export const IconMicActive = makeIconWeb(IconMicActiveSvg);
export const IconMicInactive = makeIconWeb(IconMicInactiveSvg);
export const IconMyProducts = makeIconWeb(IconMyProductsSvg);
export const IconNeurology = makeIconWeb(IconNeurologySvg);
export const IconNotification = makeIconWeb(IconNotificationSvg);
export const IconOrders = makeIconWeb(IconOrdersSvg);
export const IconPakistan = makeIconWeb(IconPakistanSvg);
export const IconPatient = makeIconWeb(IconPatientSvg);
export const IconPayment = makeIconWeb(IconPaymentSvg);
export const IconPricing = makeIconWeb(IconPricingSvg);
export const IconPrivacyPolicy = makeIconWeb(IconPrivacyPolicySvg);
export const IconProduct = makeIconWeb(IconProductSvg);
export const IconProfileActive = makeIconWeb(IconProfileActiveSvg);
export const IconProfileInActive = makeIconWeb(IconProfileInActiveSvg);
export const IconRespiratory = makeIconWeb(IconRespiratorySvg);
export const IconReturnOrders = makeIconWeb(IconReturnOrdersSvg);
export const IconReviews = makeIconWeb(IconReviewsSvg);
export const IconRightArrow = makeIconWeb(IconRightArrowSvg);
export const IconRightArrowGray = makeIconWeb(IconRightArrowGraySvg);
export const IconRightArrowWhite = makeIconWeb(IconRightArrowWhiteSvg);
export const IconSearch = makeIconWeb(IconSearchSvg);
export const IconShare = makeIconWeb(IconShareSvg);
export const IconShop = makeIconWeb(IconShopSvg);
export const IconSignOut = makeIconWeb(IconSignOutSvg);
export const IconSpecialist = makeIconWeb(IconSpecialistSvg);
export const IconTerms = makeIconWeb(IconTermsSvg);
export const IconTickCircle = makeIconWeb(IconTickCircleSvg);
export const IconToolsActive = makeIconWeb(IconToolsActiveSvg);
export const IconToolsInactive = makeIconWeb(IconToolsInactiveSvg);
export const IconTrackSales = makeIconWeb(IconTrackSalesSvg);
export const IconTrackSalesDark = makeIconWeb(IconTrackSalesDarkSvg);
export const IconTrackSalesGreen = makeIconWeb(IconTrackSalesGreenSvg);
export const IconTrackSalesLight = makeIconWeb(IconTrackSalesLightSvg);
export const IconTrackSalesYellow = makeIconWeb(IconTrackSalesYellowSvg);
export const IconUser = makeIconWeb(IconUserSvg);
export const IconVerify = makeIconWeb(IconVerifySvg);
