//  This file is auto-generated and read-only
import {makeIconWeb} from './utils/makeIconWeb';
import {ReactComponent as IconAboutSvg} from '~Assets/Icons/about.svg';
import {ReactComponent as IconAddSvg} from '~Assets/Icons/add.svg';
import {ReactComponent as IconAppinionsActiveSvg} from '~Assets/Icons/appinionsActive.svg';
import {ReactComponent as IconAppinionsInActiveSvg} from '~Assets/Icons/appinionsInActive.svg';
import {ReactComponent as IconArrowDownSvg} from '~Assets/Icons/arrowDown.svg';
import {ReactComponent as IconCardiologySvg} from '~Assets/Icons/cardiology.svg';
import {ReactComponent as IconChevronleftSvg} from '~Assets/Icons/chevronleft.svg';
import {ReactComponent as IconConvertSvg} from '~Assets/Icons/convert.svg';
import {ReactComponent as IconCrossSvg} from '~Assets/Icons/cross.svg';
import {ReactComponent as IconDermatologySvg} from '~Assets/Icons/dermatology.svg';
import {ReactComponent as IconDocumentSvg} from '~Assets/Icons/document.svg';
import {ReactComponent as IconEditSvg} from '~Assets/Icons/edit.svg';
import {ReactComponent as IconEmailSvg} from '~Assets/Icons/email.svg';
import {ReactComponent as IconEyeSvg} from '~Assets/Icons/eye.svg';
import {ReactComponent as IconEyeHideSvg} from '~Assets/Icons/eyeHide.svg';
import {ReactComponent as IconFaqsSvg} from '~Assets/Icons/faqs.svg';
import {ReactComponent as IconFeedbackSvg} from '~Assets/Icons/feedback.svg';
import {ReactComponent as IconHamburgerSvg} from '~Assets/Icons/hamburger.svg';
import {ReactComponent as IconHomeActiveSvg} from '~Assets/Icons/homeActive.svg';
import {ReactComponent as IconHomeInActiveSvg} from '~Assets/Icons/homeInActive.svg';
import {ReactComponent as IconInfoCircleSvg} from '~Assets/Icons/infoCircle.svg';
import {ReactComponent as IconLockSvg} from '~Assets/Icons/lock.svg';
import {ReactComponent as IconMedicalInfoActiveSvg} from '~Assets/Icons/medicalInfoActive.svg';
import {ReactComponent as IconMedicalInfoInActiveSvg} from '~Assets/Icons/medicalInfoInActive.svg';
import {ReactComponent as IconNeurologySvg} from '~Assets/Icons/neurology.svg';
import {ReactComponent as IconNotificationSvg} from '~Assets/Icons/notification.svg';
import {ReactComponent as IconPatientSvg} from '~Assets/Icons/patient.svg';
import {ReactComponent as IconPaymentSvg} from '~Assets/Icons/payment.svg';
import {ReactComponent as IconPricingSvg} from '~Assets/Icons/pricing.svg';
import {ReactComponent as IconPrivacyPolicySvg} from '~Assets/Icons/privacyPolicy.svg';
import {ReactComponent as IconProfileActiveSvg} from '~Assets/Icons/profileActive.svg';
import {ReactComponent as IconProfileInActiveSvg} from '~Assets/Icons/profileInActive.svg';
import {ReactComponent as IconRespiratorySvg} from '~Assets/Icons/respiratory.svg';
import {ReactComponent as IconSearchSvg} from '~Assets/Icons/search.svg';
import {ReactComponent as IconSignOutSvg} from '~Assets/Icons/signOut.svg';
import {ReactComponent as IconSpecialistSvg} from '~Assets/Icons/specialist.svg';
import {ReactComponent as IconTermsSvg} from '~Assets/Icons/terms.svg';
import {ReactComponent as IconTickCircleSvg} from '~Assets/Icons/tickCircle.svg';
import {ReactComponent as IconUserSvg} from '~Assets/Icons/user.svg';
import {ReactComponent as IconVerifySvg} from '~Assets/Icons/verify.svg';

export * from './props';

export const IconAbout = makeIconWeb(IconAboutSvg);
export const IconAdd = makeIconWeb(IconAddSvg);
export const IconAppinionsActive = makeIconWeb(IconAppinionsActiveSvg);
export const IconAppinionsInActive = makeIconWeb(IconAppinionsInActiveSvg);
export const IconArrowDown = makeIconWeb(IconArrowDownSvg);
export const IconCardiology = makeIconWeb(IconCardiologySvg);
export const IconChevronleft = makeIconWeb(IconChevronleftSvg);
export const IconConvert = makeIconWeb(IconConvertSvg);
export const IconCross = makeIconWeb(IconCrossSvg);
export const IconDermatology = makeIconWeb(IconDermatologySvg);
export const IconDocument = makeIconWeb(IconDocumentSvg);
export const IconEdit = makeIconWeb(IconEditSvg);
export const IconEmail = makeIconWeb(IconEmailSvg);
export const IconEye = makeIconWeb(IconEyeSvg);
export const IconEyeHide = makeIconWeb(IconEyeHideSvg);
export const IconFaqs = makeIconWeb(IconFaqsSvg);
export const IconFeedback = makeIconWeb(IconFeedbackSvg);
export const IconHamburger = makeIconWeb(IconHamburgerSvg);
export const IconHomeActive = makeIconWeb(IconHomeActiveSvg);
export const IconHomeInActive = makeIconWeb(IconHomeInActiveSvg);
export const IconInfoCircle = makeIconWeb(IconInfoCircleSvg);
export const IconLock = makeIconWeb(IconLockSvg);
export const IconMedicalInfoActive = makeIconWeb(IconMedicalInfoActiveSvg);
export const IconMedicalInfoInActive = makeIconWeb(IconMedicalInfoInActiveSvg);
export const IconNeurology = makeIconWeb(IconNeurologySvg);
export const IconNotification = makeIconWeb(IconNotificationSvg);
export const IconPatient = makeIconWeb(IconPatientSvg);
export const IconPayment = makeIconWeb(IconPaymentSvg);
export const IconPricing = makeIconWeb(IconPricingSvg);
export const IconPrivacyPolicy = makeIconWeb(IconPrivacyPolicySvg);
export const IconProfileActive = makeIconWeb(IconProfileActiveSvg);
export const IconProfileInActive = makeIconWeb(IconProfileInActiveSvg);
export const IconRespiratory = makeIconWeb(IconRespiratorySvg);
export const IconSearch = makeIconWeb(IconSearchSvg);
export const IconSignOut = makeIconWeb(IconSignOutSvg);
export const IconSpecialist = makeIconWeb(IconSpecialistSvg);
export const IconTerms = makeIconWeb(IconTermsSvg);
export const IconTickCircle = makeIconWeb(IconTickCircleSvg);
export const IconUser = makeIconWeb(IconUserSvg);
export const IconVerify = makeIconWeb(IconVerifySvg);
